spring:
  application:
    name: team

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/xe}
    username: ${SPRING_DATASOURCE_USERNAME:springboot}
    password: ${SPRING_DATASOURCE_PASSWORD:java1234}

  thymeleaf:
    cache: false

  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090